from xml.etree.ElementTree import Element, SubElement, Comment, tostring

class XMLBuilder(object):
    @staticmethod
    def dict(key, elem):
        d = Element('dict')
        k = SubElement(d, 'key')
        k.text = key
        d.append(elem)
        return d

class DayOneEntry(object):
    """
    This class should output the XML that will be written to DayOne.journal/entries folder
    """

    pass


"""import csv
from xml.etree.ElementTree import Element, SubElement, Comment, tostring
import datetime
from ElementTree_pretty import prettify

generated_on = str(datetime.datetime.now())

# Configure one attribute with set()
root = Element('opml')
root.set('version', '1.0')

root.append(Comment('Generated by ElementTree_csv_to_xml.py for PyMOTW'))

head = SubElement(root, 'head')
title = SubElement(head, 'title')
title.text = 'My Podcasts'
dc = SubElement(head, 'dateCreated')
dc.text = generated_on
dm = SubElement(head, 'dateModified')
dm.text = generated_on

body = SubElement(root, 'body')

with open('podcasts.csv', 'rt') as f:
    current_group = None
    reader = csv.reader(f)
    for row in reader:
        group_name, podcast_name, xml_url, html_url = row
        if current_group is None or group_name != current_group.text:
            # Start a new group
            current_group = SubElement(body, 'outline', {'text':group_name})
        # Add this podcast to the group,
        # setting all of its attributes at
        # once.
        podcast = SubElement(current_group, 'outline',
                             {'text':podcast_name,
                              'xmlUrl':xml_url,
                              'htmlUrl':html_url,
                              })

print prettify(root)"""


"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Creation Date</key>
  <date>2013-10-11T19:53:20Z</date>
  <key>Creator</key>
  <dict>
    <key>Software Agent</key>
    <string>Slogger/2.1.14</string>
  </dict>
  <key>Entry Text</key>
  <string>## Instagram Photo

Possibly the most awkward slow mo ever

### 1 Likes

Rachel Johns



#social #instagram
</string>
  <key>Location</key>
  <dict>
  <key>Administrative Area</key>
  <string></string>
  <key>Country</key>
  <string></string>
  <key>Latitude</key>
  <real>53.33739229</real>
  <key>Longitude</key>
  <real>-6.232076604</real>
  <key>Place Name</key>
  <string></string>
  </dict>
  <key>Starred</key>
  <false/>
  <key>Tags</key>
  <array>
    <string>instagram</string>
    <string>social</string>
  </array>
  <key>UUID</key>
  <string>0B240A19D26C49E28301E759C6597B5C</string>
</dict>
</plist>
"""
